

const accessApps = [
    {
      _id: "5d1a514b5d2c12c7449be001",
      nom: "INTERFACE COLLECTEUR",
      note: "",
      description: "Genère un fichier texte des commandes",
      status: "Actif",
      externe: false,
      type: "global",
      multisociete: true,
    },
    {
      _id: "5d1a514b5d2c12c7449be002",
      nom: "GLOBAL ETIQUETTES",
      note: "",
      description: "Genère des étiquettes",
      status: "Actif",
      externe: false,
      type: "global",
      multisociete: true,
    },
    {
      _id: "5d1a514b5d2c12c7449be003",
      nom: "INTERFACE GENERATEUR FICHIER",
      note: "",
      description: "Genère un fichier proformat, commandes ou factures",
      status: "Actif",
      externe: false,
      type: "global",
      multisociete: true,
    },
    {
      _id: "5d1a514b5d2c12c7449be004",
      nom: "INTERFACE COLLECTEUR MANUEL",
      note: "",
      description: "Genère un fichier texte des commandes",
      status: "Actif",
      externe: false,
      type: "global",
      multisociete: true,
    },
    {
      _id: "5d1a514b5d2c12c7449be005",
      nom: "INTERFACE RELANCE FOURNISSEUR",
      note: "",
      description: "ENVOIE UN MAIL DE RELANCE AU FOURNISSEUR",
      status: "Actif",
      externe: false,
      type: "global",
      multisociete: true,
    },
    {
      _id: "5d1a514b5d2c12c7449be006",
      nom: "INTERFACE NOUVEAUX PV TGC",
      note: "",
      description: "CALCUL LES NOUVEAUX PRIX DE VENTE",
      status: "Actif",
      externe: false,
      type: "global",
      multisociete: true,
    },
    {
      _id: "5d1a514b5d2c12c7449be007",
      nom: "QC CATALOGUE PHOTOS",
      note: "",
      description: "AFFICHE LE CATALOGUE PHOTO DES ARTICLES",
      status: "Actif",
      externe: false,
      type: "global",
      multisociete: false,
    },
    {
      _id: "5d1a514b5d2c12c7449be008",
      nom: "TGC HD NOUVEAUX PV TGC",
      note: "",
      description: "CALCUL LES NOUVEAUX PRIX DE VENTES",
      status: "Actif",
      externe: false,
      type: "global",
      multisociete: false,
    },
    {
      _id: "5d1a514b5d2c12c7449be009",
      nom: "GENDOUBL",
      note: "",
      description: "RECHERCHE LE OU LES GENDOUBL D'UN ARTICLE",
      status: "Actif",
      externe: false,
      type: "global",
      multisociete: false,
    },
    {
      _id: "5d1a514b5d2c12c7449be010",
      nom: "LOCALISATION INVENTAIRE 2022",
      note: "",
      description: "Localisation des articles après inventaire 2022",
      status: "Actif",
      externe: false,
      type: "global",
      multisociete: false,
    },
    {
      _id: "5d1a514b5d2c12c7449be011",
      nom: "LOCALISATION INVENTAIRE 2023",
      note: "",
      description: "Localisation des articles après inventaire 2023",
      status: "Actif",
      externe: false,
      type: "global",
      multisociete: false,
    }
   
  ];
  
  export default accessApps;
  