const masterRepports = [
  {
    _id: "64bdf6f9c12f3d1e9a8b4567",
    nom: "genETA",
    note: "",
    description: "Genère les rapports d'ETA",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4568",
    nom: "AlerteProforma",
    note: "",
    description: "Genère les commandes clients prêtes ou a facturer",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4569",
    nom: "Nouveautes",
    note: "",
    description: "Genère les nouvelles entrées",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4570",
    nom: "NewEntrees",
    note: "",
    description: "Genère le catalogue des nouveauté entrées",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4571",
    nom: "ResaSurEntrees",
    note: "",
    description: "Genère les Resa sur les nouvelles entrées",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4572",
    nom: "NewListeSpecial",
    note: "",
    description: "Genère les changement de prix spéciaux",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4573",
    nom: "TarifClient",
    note: "",
    description: "Genère les tarifs clients impactés par le changement de PV",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4574",
    nom: "SuiviPV",
    note: "",
    description: "Genère les changement de prix de vente magasin",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4575",
    nom: "RegulInvJour",
    note: "",
    description: "Genère la regul d'inventaire",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4576",
    nom: "EditFactureAuto",
    note: "",
    description: "Genère les facture groupe",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4577",
    nom: "JournalCaisseJour",
    note: "",
    description: "Genère le journal de caisse du jour",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4578",
    nom: "JournalReglementJour",
    note: "",
    description: "Genère les règlement du jour",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4579",
    nom: "JournalCaisseJourApresMidi",
    note: "",
    description: "Genère le journal de caisse de l'après midi",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4580",
    nom: "JournalCaisseJourMatin",
    note: "",
    description: "Genère le journal de caisse du matin",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4581",
    nom: "VerifTGC",
    note: "",
    description: "Alerte des articles sans TGC",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4582",
    nom: "AlerteErreurDateFacture",
    note: "",
    description:
      "Alerte des factures qui ont été facturé a des date différentes de la date du jour",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4583",
    nom: "AlerteErreurTGCFacture",
    note: "",
    description: "Alerte TGC a 0",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4584",
    nom: "CommunicationClientFacture",
    note: "",
    description: "Envois les factures aux clients concernés",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4585",
    nom: "AddArtPlusValues",
    note: "",
    description: "N/A",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4586",
    nom: "AlerteModeReglementFacture",
    note: "",
    description:
      "Alerte concernant les factures n'ayant pas de mode de règlement renseigné",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4587",
    nom: "ComISEE",
    note: "",
    description: "Relevé ISEE prix HT",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4588",
    nom: "ReapproMagScebMecalac",
    note: "",
    description: "N/A",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4589",
    nom: "RechDoublons",
    note: "",
    description: "N/A",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4590",
    nom: "NewEntreesMois",
    note: "",
    description: "N/A",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4591",
    nom: "ResaMensuelleFramente",
    note: "",
    description: "N/A",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4592",
    nom: "ResaMensuelleTotal",
    note: "",
    description: "N/A",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4593",
    nom: "VentePromoMensuelle",
    note: "",
    description: "N/A",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4594",
    nom: "DefineArticlePromo",
    note: "",
    description: "N/A",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4595",
    nom: "CommunicationClientNewsLetterMensuel",
    note: "",
    description: "N/A",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4596",
    nom: "RapportTGC",
    note: "",
    description: "Genère les rapports TGC",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4597",
    nom: "ConsolidStatsCommerciaux",
    note: "",
    description: "Genère les stats commerciaux",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4598",
    nom: "RapportTGCMensuel",
    note: "",
    description: "N/A",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4599",
    nom: "CommunicationClientRapportTGC",
    note: "",
    description: "N/A",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4600",
    nom: "ReapproMagSCEBMecalac",
    note: "",
    description: "N/A",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4601",
    nom: "RechDoublons",
    note: "",
    description: "N/A",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4602",
    nom: "RecapNbCommande",
    note: "",
    description: "N/A",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4603",
    nom: "DefineArticlePromo",
    note: "",
    description: "N/A",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4604",
    nom: "SendBalances",
    note: "",
    description: "N/A",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4605",
    nom: "ExportReapproImportNew",
    note: "",
    description: "N/A",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4606",
    nom: "ExportReapproMagNew",
    note: "",
    description: "N/A",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4607",
    nom: "ReapproMagGroupePrioritaire",
    note: "",
    description: "N/A",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4608",
    nom: "VentePromoHebdo",
    note: "",
    description: "N/A",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4609",
    nom: "SuiviActivCmd",
    note: "",
    description: "N/A",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4610",
    nom: "RecapActiviteCmd",
    note: "",
    description: "N/A",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4611",
    nom: "NewEntreesHebdo",
    note: "",
    description: "N/A",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4612",
    nom: "SuiviDeprec",
    note: "",
    description: "N/A",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4613",
    nom: "ReapproFiliales",
    note: "",
    description: "N/A",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4614",
    nom: "ReapproLocalHebdo",
    note: "",
    description: "N/A",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
  {
    _id: "64bdf6f9c12f3d1e9a8b4615",
    nom: "ReapproLocalRuptureHebdo",
    note: "",
    description: "N/A",
    status: "Actif",
    externe: false,
    type: "master",
    multisociete: true,
  },
];

export default masterRepports;
